INSERT INTO tb_product(name) VALUES ('Barry Allen');
INSERT INTO tb_product(name) VALUES ('Logan');
INSERT INTO tb_product(name) VALUES ('Padme');
INSERT INTO tb_product(name) VALUES ('Padme');
INSERT INTO tb_product(name) VALUES ('Logan');
INSERT INTO tb_product(name) VALUES ('Kal-El');
INSERT INTO tb_product(name) VALUES ('Kal-El');
INSERT INTO tb_product(name) VALUES ('Anakin');
INSERT INTO tb_product(name) VALUES ('Barry Alle2');
INSERT INTO tb_product(name) VALUES ('Kal-El');
INSERT INTO tb_product(name) VALUES ('Logan');
INSERT INTO tb_product(name) VALUES ('Barry Alle6');
INSERT INTO tb_product(name) VALUES ('Logan');
INSERT INTO tb_product(name) VALUES ('Anakin');
INSERT INTO tb_product(name) VALUES ('Padme');
INSERT INTO tb_product(name) VALUES ('Logan');
INSERT INTO tb_product(name) VALUES ('Kal-El');
INSERT INTO tb_product(name) VALUES ('Kal-El');
INSERT INTO tb_product(name) VALUES ('Anakin');
INSERT INTO tb_product(name) VALUES ('Padme');
INSERT INTO tb_product(name) VALUES ('Logan');
INSERT INTO tb_product(name) VALUES ('Padme');
INSERT INTO tb_product(name) VALUES ('Barry Alle9');
INSERT INTO tb_product(name) VALUES ('Kal-El');
INSERT INTO tb_product(name) VALUES ('Anakin');
INSERT INTO tb_product(name) VALUES ('Kal-El');
INSERT INTO tb_product(name) VALUES ('Logan');
INSERT INTO tb_product(name) VALUES ('Barry Alle9');
INSERT INTO tb_product(name) VALUES ('Logan');
INSERT INTO tb_product(name) VALUES ('Anakin');
INSERT INTO tb_product(name) VALUES ('Logan');
INSERT INTO tb_product(name) VALUES ('Logan');
INSERT INTO tb_product(name) VALUES ('Logan');
INSERT INTO tb_product(name) VALUES ('Barry Alle5');
INSERT INTO tb_product(name) VALUES ('Barry Alle2');
INSERT INTO tb_product(name) VALUES ('Logan');
INSERT INTO tb_product(name) VALUES ('Padme');
INSERT INTO tb_product(name) VALUES ('Barry Alle7');
INSERT INTO tb_product(name) VALUES ('Logan');
INSERT INTO tb_product(name) VALUES ('Kal-El');
INSERT INTO tb_product(name) VALUES ('Kal-El');
INSERT INTO tb_product(name) VALUES ('Padme');
INSERT INTO tb_product(name) VALUES ('Anakin');
INSERT INTO tb_product(name) VALUES ('Anakin');
INSERT INTO tb_product(name) VALUES ('Barry Alle6');
INSERT INTO tb_product(name) VALUES ('Kal-El');
INSERT INTO tb_product(name) VALUES ('Padme');
INSERT INTO tb_product(name) VALUES ('Barry Alle5');
INSERT INTO tb_product(name) VALUES ('Kal-El');
INSERT INTO tb_product(name) VALUES ('Kal-El');
INSERT INTO tb_product(name) VALUES ('Padme');
INSERT INTO tb_product(name) VALUES ('Kal-El');
INSERT INTO tb_product(name) VALUES ('Anakin');
INSERT INTO tb_product(name) VALUES ('Anakin');
INSERT INTO tb_product(name) VALUES ('Barry Alle0');
INSERT INTO tb_product(name) VALUES ('Anakin');
INSERT INTO tb_product(name) VALUES ('Padme');
INSERT INTO tb_product(name) VALUES ('Padme');
INSERT INTO tb_product(name) VALUES ('Logan');
INSERT INTO tb_product(name) VALUES ('Logan');
INSERT INTO tb_product(name) VALUES ('Padme');
INSERT INTO tb_product(name) VALUES ('Barry Alle2');
INSERT INTO tb_product(name) VALUES ('Anakin');
INSERT INTO tb_product(name) VALUES ('Kal-El');
INSERT INTO tb_product(name) VALUES ('Padme');
INSERT INTO tb_product(name) VALUES ('Padme');
INSERT INTO tb_product(name) VALUES ('Logan');
INSERT INTO tb_product(name) VALUES ('Kal-El');
INSERT INTO tb_product(name) VALUES ('Logan');
INSERT INTO tb_product(name) VALUES ('Anakin');
INSERT INTO tb_product(name) VALUES ('Anakin');
INSERT INTO tb_product(name) VALUES ('Anakin');
INSERT INTO tb_product(name) VALUES ('Logan');
INSERT INTO tb_product(name) VALUES ('Anakin');
INSERT INTO tb_product(name) VALUES ('Barry Alle3');
INSERT INTO tb_product(name) VALUES ('Anakin');
INSERT INTO tb_product(name) VALUES ('Barry Alle7');
INSERT INTO tb_product(name) VALUES ('Kal-El');
INSERT INTO tb_product(name) VALUES ('Barry Alle5');
INSERT INTO tb_product(name) VALUES ('Barry Alle9');
INSERT INTO tb_product(name) VALUES ('Kal-El');
INSERT INTO tb_product(name) VALUES ('Kal-El');
INSERT INTO tb_product(name) VALUES ('Kal-El');
INSERT INTO tb_product(name) VALUES ('Anakin');
INSERT INTO tb_product(name) VALUES ('Kal-El');
INSERT INTO tb_product(name) VALUES ('Anakin');
INSERT INTO tb_product(name) VALUES ('Padme');
INSERT INTO tb_product(name) VALUES ('Kal-El');
INSERT INTO tb_product(name) VALUES ('Kal-El');
INSERT INTO tb_product(name) VALUES ('Barry Alle8');
INSERT INTO tb_product(name) VALUES ('Logan');
INSERT INTO tb_product(name) VALUES ('Logan');
INSERT INTO tb_product(name) VALUES ('Anakin');
INSERT INTO tb_product(name) VALUES ('Barry Alle4');
INSERT INTO tb_product(name) VALUES ('Kal-El');
INSERT INTO tb_product(name) VALUES ('Padme');
INSERT INTO tb_product(name) VALUES ('Anakin');
INSERT INTO tb_product(name) VALUES ('Anakin');
INSERT INTO tb_product(name) VALUES ('Logan');
INSERT INTO tb_product(name) VALUES ('Anakin');
INSERT INTO tb_product(name) VALUES ('Logan');
INSERT INTO tb_product(name) VALUES ('Padme');
INSERT INTO tb_product(name) VALUES ('Anakin');
INSERT INTO tb_product(name) VALUES ('Anakin');
INSERT INTO tb_product(name) VALUES ('Anakin');
INSERT INTO tb_product(name) VALUES ('Barry Alle3');
INSERT INTO tb_product(name) VALUES ('Barry Alle1');
INSERT INTO tb_product(name) VALUES ('Barry Alle2');
INSERT INTO tb_product(name) VALUES ('Kal-El');
INSERT INTO tb_product(name) VALUES ('Kal-El');
INSERT INTO tb_product(name) VALUES ('Padme');
INSERT INTO tb_product(name) VALUES ('Logan');
INSERT INTO tb_product(name) VALUES ('Padme');
INSERT INTO tb_product(name) VALUES ('Padme');
INSERT INTO tb_product(name) VALUES ('Kal-El');
INSERT INTO tb_product(name) VALUES ('Anakin');
INSERT INTO tb_product(name) VALUES ('Padm7');